Vagrant.configure("2") do |config|
  config.vm.box = "janobono/xenial64-sqlserver2017"
  config.vm.box_version = "1.0.0"

  config.vm.network "forwarded_port", guest: 1433, host: 1433
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    #   # Customize the amount of memory on the VM:
    vb.memory = "4096"
	vb.cpus = 2
	
	vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
	vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
	vb.customize ["modifyvm", :id, "--vram", "64"]
	
  end
  
end